const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#00D4AA",
    background: "#0A0F1E",
    foreground: "#FFFFFF",
    card: "#0F1629",
    cardForeground: "#FFFFFF",
    primary: "#00D4AA",
    primaryForeground: "#0A0F1E",
    secondary: "#1A2240",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2240",
    mutedForeground: "#8895B3",
    accent: "#F5C518",
    accentForeground: "#0A0F1E",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#1E2D50",
    input: "#1A2240",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00D4AA",
    background: "#0A0F1E",
    foreground: "#FFFFFF",
    card: "#0F1629",
    cardForeground: "#FFFFFF",
    primary: "#00D4AA",
    primaryForeground: "#0A0F1E",
    secondary: "#1A2240",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2240",
    mutedForeground: "#8895B3",
    accent: "#F5C518",
    accentForeground: "#0A0F1E",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#1E2D50",
    input: "#1A2240",
  },
  radius: 12,
};

export default colors;
