-- =====================================================
-- MIGRATION 001: INITIAL TRADING PLATFORM SCHEMA
-- =====================================================
-- Date: 2026-05-15
-- Description: Create core tables for trading platform
-- Version: 1.0.0

-- =====================================================
-- CORE TABLES FOR TRADING PLATFORM
-- =====================================================

-- Users Table (Multi-tenant support)
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  hashed_password TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  role TEXT DEFAULT 'user', -- 'user', 'admin', 'compliance'
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
COMMENT ON TABLE users IS 'Multi-tenant user accounts with role-based access control';

-- Trading Accounts (Broker-linked accounts)
CREATE TABLE IF NOT EXISTS trading_accounts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  broker_name TEXT NOT NULL, -- 'zerodha', 'upstox', 'shoonya'
  account_id TEXT NOT NULL,
  api_key TEXT, -- Encrypted at application level
  api_secret TEXT, -- Encrypted at application level
  access_token TEXT, -- Encrypted, refreshed periodically
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, broker_name, account_id)
);
COMMENT ON TABLE trading_accounts IS 'Broker-linked trading accounts for each user';

-- Strategies (Trading strategies configuration)
CREATE TABLE IF NOT EXISTS strategies (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  strategy_type TEXT NOT NULL, -- 'momentum', 'mean_reversion', 'arbitrage', 'ml_model'
  config JSONB NOT NULL, -- Strategy parameters: {thresholds, timeframes, etc}
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
COMMENT ON TABLE strategies IS 'Trading strategy definitions with configuration';

-- Signals (Generated trading signals)
CREATE TABLE IF NOT EXISTS signals (
  id SERIAL PRIMARY KEY,
  strategy_id INTEGER REFERENCES strategies(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  action TEXT NOT NULL, -- 'BUY', 'SELL', 'HOLD'
  confidence DECIMAL(5, 2), -- 0-100 percentage
  reasoning JSONB, -- Array of reasoning strings
  risk_level TEXT, -- 'LOW', 'MEDIUM', 'HIGH'
  expected_return DECIMAL(5, 4),
  stop_loss DECIMAL(10, 2),
  target_price DECIMAL(10, 2),
  market_data JSONB, -- Technical indicators snapshot
  signal_status TEXT DEFAULT 'pending', -- 'pending', 'triggered', 'executed', 'expired'
  created_at TIMESTAMP DEFAULT NOW()
);
COMMENT ON TABLE signals IS 'Trading signals generated by algorithms';

-- Orders (Executed orders)
CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  signal_id INTEGER REFERENCES signals(id) ON DELETE SET NULL,
  trading_account_id INTEGER REFERENCES trading_accounts(id) ON DELETE RESTRICT,
  order_id TEXT UNIQUE NOT NULL, -- Broker's order ID
  symbol TEXT NOT NULL,
  side TEXT NOT NULL, -- 'BUY', 'SELL'
  quantity INTEGER NOT NULL,
  price DECIMAL(10, 2),
  order_type TEXT NOT NULL, -- 'MARKET', 'LIMIT', 'SL', 'SL-M'
  product TEXT NOT NULL, -- 'CNC' (Delivery), 'MIS' (Intraday), 'NRML' (Options)
  exchange TEXT NOT NULL, -- 'NSE', 'NFO', 'BSE'
  status TEXT NOT NULL, -- 'PENDING', 'EXECUTED', 'REJECTED', 'CANCELLED'
  executed_price DECIMAL(10, 2),
  executed_quantity INTEGER,
  slippage DECIMAL(5, 4),
  broker_charges DECIMAL(10, 2),
  execution_time TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);
COMMENT ON TABLE orders IS 'Executed trading orders with full audit trail';

-- Positions (Current holdings)
CREATE TABLE IF NOT EXISTS positions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  trading_account_id INTEGER REFERENCES trading_accounts(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  avg_price DECIMAL(10, 2) NOT NULL,
  current_price DECIMAL(10, 2),
  market_value DECIMAL(15, 2),
  unrealized_pnl DECIMAL(15, 2),
  realized_pnl DECIMAL(15, 2),
  last_updated TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, trading_account_id, symbol)
);
COMMENT ON TABLE positions IS 'Current open positions and holdings';

-- Daily Performance Tracking
CREATE TABLE IF NOT EXISTS daily_performance (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  trading_account_id INTEGER REFERENCES trading_accounts(id) ON DELETE CASCADE,
  date TIMESTAMP NOT NULL,
  portfolio_value DECIMAL(15, 2),
  daily_pnl DECIMAL(10, 2),
  cumulative_pnl DECIMAL(15, 2),
  max_drawdown DECIMAL(5, 4),
  sharpe_ratio DECIMAL(5, 2),
  win_rate DECIMAL(5, 4),
  total_trades INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, trading_account_id, date)
);
COMMENT ON TABLE daily_performance IS 'Daily aggregated performance metrics';

-- Risk Limits (Per-user risk configuration)
CREATE TABLE IF NOT EXISTS risk_limits (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  max_portfolio_risk DECIMAL(5, 4) DEFAULT 0.05, -- 5% default
  max_drawdown_limit DECIMAL(5, 4) DEFAULT 0.08, -- 8% default
  max_position_size DECIMAL(5, 4) DEFAULT 0.20, -- 20% default
  max_daily_loss DECIMAL(5, 4) DEFAULT 0.03, -- 3% default
  max_concentration DECIMAL(5, 4) DEFAULT 0.30, -- 30% default
  min_margin_buffer DECIMAL(5, 4) DEFAULT 0.25, -- 25% default
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id)
);
COMMENT ON TABLE risk_limits IS 'Per-user risk management limits';

-- Audit Log (Compliance & monitoring)
CREATE TABLE IF NOT EXISTS audit_log (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL, -- 'LOGIN', 'TRADE', 'SIGNAL', 'CONFIG_CHANGE', 'RISK_BREACH'
  details JSONB,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);
COMMENT ON TABLE audit_log IS 'Complete audit trail for compliance and monitoring';

-- =====================================================
-- PERFORMANCE & MAINTENANCE TABLES
-- =====================================================

-- Trade History (Archive table for completed trades)
CREATE TABLE IF NOT EXISTS trade_history (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  trading_account_id INTEGER REFERENCES trading_accounts(id) ON DELETE CASCADE,
  order_id TEXT,
  symbol TEXT NOT NULL,
  side TEXT NOT NULL,
  quantity INTEGER,
  entry_price DECIMAL(10, 2),
  exit_price DECIMAL(10, 2),
  pnl DECIMAL(15, 2),
  pnl_percentage DECIMAL(5, 4),
  duration_seconds INTEGER,
  closed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);
COMMENT ON TABLE trade_history IS 'Historical record of closed trades for analysis';

-- Market Data Cache (Real-time market data)
CREATE TABLE IF NOT EXISTS market_data_cache (
  id SERIAL PRIMARY KEY,
  symbol TEXT NOT NULL,
  ltp DECIMAL(10, 2), -- Last Traded Price
  open_price DECIMAL(10, 2),
  high_price DECIMAL(10, 2),
  low_price DECIMAL(10, 2),
  volume BIGINT,
  timestamp TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(symbol, timestamp)
);
COMMENT ON TABLE market_data_cache IS 'Cached market data for backtesting and analysis';

-- System Health Monitoring
CREATE TABLE IF NOT EXISTS system_health (
  id SERIAL PRIMARY KEY,
  check_name TEXT NOT NULL,
  status TEXT, -- 'healthy', 'warning', 'critical'
  details JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);
COMMENT ON TABLE system_health IS 'System health status and diagnostics';

-- =====================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_trading_accounts_user_id ON trading_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_strategies_user_id ON strategies(user_id);
CREATE INDEX IF NOT EXISTS idx_signals_strategy_id ON signals(strategy_id);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_positions_user_id ON positions(user_id);
CREATE INDEX IF NOT EXISTS idx_daily_performance_user_id ON daily_performance(user_id);
CREATE INDEX IF NOT EXISTS idx_daily_performance_date ON daily_performance(date);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_market_data_symbol ON market_data_cache(symbol);
CREATE INDEX IF NOT EXISTS idx_trade_history_user_id ON trade_history(user_id);

-- =====================================================
-- MIGRATE EXISTING DRIZZLE SCHEMA (if needed)
-- =====================================================
-- Note: If migrating from existing Drizzle schema, run:
-- ALTER TABLE existing_table ADD COLUMN new_column TYPE;
