// Database schema for algorithmic trading platform

import { pgTable, serial, text, integer, decimal, timestamp, boolean, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Users table (for multi-user support)
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  hashedPassword: text("hashed_password").notNull(),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Trading accounts (linked to broker accounts)
export const tradingAccounts = pgTable("trading_accounts", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  brokerName: text("broker_name").notNull(), // "zerodha", "upstox", etc.
  accountId: text("account_id").notNull(),
  apiKey: text("api_key"), // Encrypted
  apiSecret: text("api_secret"), // Encrypted
  accessToken: text("access_token"), // Encrypted, refreshed periodically
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// Strategies table
export const strategies = pgTable("strategies", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  name: text("name").notNull(),
  description: text("description"),
  config: jsonb("config"), // Strategy parameters
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Signals generated by algorithms
export const signals = pgTable("signals", {
  id: serial("id").primaryKey(),
  strategyId: integer("strategy_id").references(() => strategies.id),
  symbol: text("symbol").notNull(),
  action: text("action").notNull(), // "BUY", "SELL", "HOLD"
  confidence: decimal("confidence", { precision: 5, scale: 2 }),
  reasoning: jsonb("reasoning"), // Array of reasoning strings
  riskLevel: text("risk_level"), // "LOW", "MEDIUM", "HIGH"
  expectedReturn: decimal("expected_return", { precision: 5, scale: 4 }),
  stopLoss: decimal("stop_loss", { precision: 10, scale: 2 }),
  targetPrice: decimal("target_price", { precision: 10, scale: 2 }),
  marketData: jsonb("market_data"), // Technical indicators at signal time
  createdAt: timestamp("created_at").defaultNow(),
});

// Orders executed
export const orders = pgTable("orders", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  signalId: integer("signal_id").references(() => signals.id),
  tradingAccountId: integer("trading_account_id").references(() => tradingAccounts.id),
  orderId: text("order_id").notNull(), // Broker's order ID
  symbol: text("symbol").notNull(),
  side: text("side").notNull(), // "BUY", "SELL"
  quantity: integer("quantity").notNull(),
  price: decimal("price", { precision: 10, scale: 2 }),
  orderType: text("order_type").notNull(), // "MARKET", "LIMIT", "SL", "SL-M"
  product: text("product").notNull(), // "CNC", "MIS", "NRML"
  exchange: text("exchange").notNull(), // "NSE", "NFO"
  status: text("status").notNull(), // "PENDING", "EXECUTED", "REJECTED", "CANCELLED"
  executedPrice: decimal("executed_price", { precision: 10, scale: 2 }),
  executedQuantity: integer("executed_quantity"),
  slippage: decimal("slippage", { precision: 5, scale: 4 }),
  brokerCharges: decimal("broker_charges", { precision: 10, scale: 2 }),
  executionTime: timestamp("execution_time"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Positions (current holdings)
export const positions = pgTable("positions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  tradingAccountId: integer("trading_account_id").references(() => tradingAccounts.id),
  symbol: text("symbol").notNull(),
  quantity: integer("quantity").notNull(),
  avgPrice: decimal("avg_price", { precision: 10, scale: 2 }).notNull(),
  currentPrice: decimal("current_price", { precision: 10, scale: 2 }),
  marketValue: decimal("market_value", { precision: 10, scale: 2 }),
  unrealizedPnL: decimal("unrealized_pnl", { precision: 10, scale: 2 }),
  realizedPnL: decimal("realized_pnl", { precision: 10, scale: 2 }),
  lastUpdated: timestamp("last_updated").defaultNow(),
});

// Daily performance tracking
export const dailyPerformance = pgTable("daily_performance", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  date: timestamp("date").notNull(),
  portfolioValue: decimal("portfolio_value", { precision: 15, scale: 2 }),
  dailyPnL: decimal("daily_pnl", { precision: 10, scale: 2 }),
  cumulativePnL: decimal("cumulative_pnl", { precision: 15, scale: 2 }),
  maxDrawdown: decimal("max_drawdown", { precision: 5, scale: 4 }),
  sharpeRatio: decimal("sharpe_ratio", { precision: 5, scale: 2 }),
  winRate: decimal("win_rate", { precision: 5, scale: 4 }),
  totalTrades: integer("total_trades"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Risk limits per user
export const riskLimits = pgTable("risk_limits", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  maxPortfolioRisk: decimal("max_portfolio_risk", { precision: 5, scale: 4 }).default("0.05"), // 5%
  maxDrawdownLimit: decimal("max_drawdown_limit", { precision: 5, scale: 4 }).default("0.08"), // 8%
  maxPositionSize: decimal("max_position_size", { precision: 5, scale: 4 }).default("0.20"), // 20%
  maxDailyLoss: decimal("max_daily_loss", { precision: 5, scale: 4 }).default("0.03"), // 3%
  maxConcentration: decimal("max_concentration", { precision: 5, scale: 4 }).default("0.30"), // 30%
  minMarginBuffer: decimal("min_margin_buffer", { precision: 5, scale: 4 }).default("0.25"), // 25%
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Audit log for compliance
export const auditLog = pgTable("audit_log", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  action: text("action").notNull(), // "LOGIN", "TRADE", "SIGNAL", etc.
  details: jsonb("details"),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Zod schemas for validation
export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true, updatedAt: true });
export const insertTradingAccountSchema = createInsertSchema(tradingAccounts).omit({ id: true, createdAt: true });
export const insertStrategySchema = createInsertSchema(strategies).omit({ id: true, createdAt: true, updatedAt: true });
export const insertSignalSchema = createInsertSchema(signals).omit({ id: true, createdAt: true });
export const insertOrderSchema = createInsertSchema(orders).omit({ id: true, createdAt: true });
export const insertPositionSchema = createInsertSchema(positions).omit({ id: true, lastUpdated: true });
export const insertDailyPerformanceSchema = createInsertSchema(dailyPerformance).omit({ id: true, createdAt: true });
export const insertRiskLimitsSchema = createInsertSchema(riskLimits).omit({ id: true, createdAt: true, updatedAt: true });
export const insertAuditLogSchema = createInsertSchema(auditLog).omit({ id: true, createdAt: true });

// Types
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type TradingAccount = typeof tradingAccounts.$inferSelect;
export type InsertTradingAccount = z.infer<typeof insertTradingAccountSchema>;
export type Strategy = typeof strategies.$inferSelect;
export type InsertStrategy = z.infer<typeof insertStrategySchema>;
export type Signal = typeof signals.$inferSelect;
export type InsertSignal = z.infer<typeof insertSignalSchema>;
export type Order = typeof orders.$inferSelect;
export type InsertOrder = z.infer<typeof insertOrderSchema>;
export type Position = typeof positions.$inferSelect;
export type InsertPosition = z.infer<typeof insertPositionSchema>;
export type DailyPerformance = typeof dailyPerformance.$inferSelect;
export type InsertDailyPerformance = z.infer<typeof insertDailyPerformanceSchema>;
export type RiskLimit = typeof riskLimits.$inferSelect;
export type InsertRiskLimit = z.infer<typeof insertRiskLimitsSchema>;
export type AuditLog = typeof auditLog.$inferSelect;
export type InsertAuditLog = z.infer<typeof insertAuditLogSchema>;